### ISSUE TITLE
Change the transcription aux equation  [sf#22]

### ISSUE THREAD

**Issue by murrayrm** [BuildACell/txtlsim#22]
**Reported by tiberium87 on 2014-09-14 11:17 UTC**
Change it from CUTP:AGTP:RNAP70:DNA -> RNAP70 + DNA 

to 

CUTP:AGTP:RNAP70:DNA -> RNAP70:DNA 

before running the parameter estimation package on it. This corresponds to the for of equations derived for the Model Reduction paper.

**Comment by murrayrm** [comment]
**Commented by tiberium87 on 2014-09-14 11:20 UTC**
But don't do it until the parameter estimation is ready to run, since without re-fitting of parameters, it will mess up the predictive capability of the toolbox, since the current parameters are fitted to the original form.

**Comment by vipulsinghal02** [comment]
I think this one is done, and can be closed. Will refit data once I have the MCMC subtoolbox added, but that is all part of issue #34 .

**Comment by vipulsinghal02** [comment]
This was completed in commit 6d8338b4e84cdf548129fc2ddbfdc8ee812b5e1c
