### ISSUE TITLE
Numerical issues due to high stoichiometry coefficients

### ISSUE THREAD

**Issue by murrayrm** [BuildACell/txtlsim#36]
**Posted by Zoltan Tuza - 2012-10-08**
By Jongmin:
The current implementation of transcription and translation reaction leads
to stiffness (and numerical issues) due to high reaction-orders in the
forward reaction:
\ kf kcat
e.g. DNA:RNAP + 10 NTP <-> DNA:RNAP:NTP -> DNA + RNAP + RNA
kr
Forward binding reaction should be a simple bimolecular reaction at
elementary steps. Once we change the stoichiometry of NTP to 1, there's no
warning for stiffness by ODE solver.
As an example, the following paper describes the transcription reaction at
1-base resolution.
http://www.ncbi.nlm.nih.gov/pubmed/11460245
We don't want to go down to single base resolution. The main message to
take from this reference is that there is a fixed maximum transcription
rate for RNAP which is realized for 'HIGH-ENOUGH' NTP concentrations (with
KM on the order of 0.1 mM). So the transcription rate is constant for the
initial few hours until the NTP level drops close to KM of 0.1 mM.
Thus, the following formulation would be appropriate for RNA production rate
kf kcat
DNA:RNAP + NTP <-> DNA:RNAP:NTP -> DNA + RNAP + RNA
kr
where KM is on the order of 0.1 mM and kcat is normalized by RNA length in
100-base units (N). This leaves the question of how to achieve correct NTP
stoichiometry.
I have not thought it through, but a dummy reaction like the following may
be necessary.
kf (N-1)*kcat
DNA:RNAP + NTP <-> DNA:RNAP:NTP -> DNA + RNAP
kr

**Comment by murrayrm** [comment]
**Posted by Richard Murray - 2012-10-08**
This approach sounds reasonable as a mechanism for incorporating differing length of transcripts without creating stiff equations. One possibility would be to add an option that allows different methods of including NTP reactions and then trying out the one above.
Another, somewhat related issue, is separating out energy sources (ATP/GTP) from materials resources (all NTPs). Any thoughts?

**Comment by murrayrm** [comment]
**Posted by Jongmin - 2012-10-08**
The main thing we need to account for in terms of energy usage would be translation.
According to a following reference
http://www.med.ufl.edu/biochem/bch4024/kevinbrown/july25.pdf
1 ATP->AMP per AA charging
1 ATP->ADP, 1 GTP->GDP for initiation
1 GTP->GDP for elongation (per step)
1 GTP->GDP for termination
So for 300 aa protein, 301 ATP and 302 GTP will be consumed. We can approximate by saying 1 aa = 1 ATP + 1 GTP.
Some degradation mechanisms also use energy: e.g., RecBCD uses 2-3 ATP per base.
http://www.nature.com/nature/journal/v432/n7014/full/nature02988.html
There is an energy regenerating system in TXTL. I'm not entirely familiar with it though.
The current initial condition for TXTL kit is 1.5mM ATP, 1.5mM GTP, 0.9mM UTP, 0.9mM CTP.

**Comment by murrayrm** [comment]
I think many of these items have been addressed in the current toolbox, so we may be able to close this issue.  There is a related issue on documenting numerical instabilities (issue #35).

**Comment by vipulsinghal02** [comment]
Okay, I will have a look at whatever needs to be done documentation wise (probably just a short section in the PDF documentation), and we can try to close this issue soon if everything looks good.

**Comment by vipulsinghal02** [comment]
I think this issue is a subset of the more general numerical stability issue question. The numerical stability issues I refer to in #35 are the stiffness type things that lead to integration tolerance problems under certain parameter value combinations.

**Comment by vipulsinghal02** [comment]
@murrayrm 

I think we can close this. This is basically the use of consumption reactions to take care of the large stoichiometric coefficients in the transcription and translation reactions. I updated this in the recent commit 6d8338b4e84cdf548129fc2ddbfdc8ee812b5e1c .

This needs to be documented in the documentation, but that is a documentation issue we can address in issue #35 .
